"""unique attribute

Revision ID: 00535737e77a
Revises: 9bc7fae3a2ee
Create Date: 2023-03-07 11:48:50.345796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00535737e77a'
down_revision = '9bc7fae3a2ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
