"""revisions

Revision ID: 018ed12412fe
Revises: 0aef2e6ae23f
Create Date: 2023-03-16 13:23:08.058942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '018ed12412fe'
down_revision = '0aef2e6ae23f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
