"""fix error

Revision ID: 01b0be59fced
Revises: 1be86fb46240
Create Date: 2023-03-16 14:08:13.281218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01b0be59fced'
down_revision = '1be86fb46240'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
