"""unique attribute

Revision ID: 07b08190e205
Revises: de86b58f1054
Create Date: 2023-03-07 12:36:44.890708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07b08190e205'
down_revision = 'de86b58f1054'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
