"""Updated teacher/students and parent/child relationship

Revision ID: 08af7e40b2a1
Revises: 9b4b035419b4
Create Date: 2023-03-07 08:22:06.369887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08af7e40b2a1'
down_revision = '9b4b035419b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('administrators_student_id_fkey', 'administrators', type_='foreignkey')
    op.drop_column('administrators', 'student_id')
    op.drop_constraint('guardians_child_id_fkey', 'guardians', type_='foreignkey')
    op.drop_column('guardians', 'child_id')
    op.add_column('students', sa.Column('parent_id', sa.Integer(), nullable=False))
    op.add_column('students', sa.Column('teacher_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'students', 'guardians', ['parent_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'students', 'administrators', ['teacher_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.drop_column('students', 'teacher_id')
    op.drop_column('students', 'parent_id')
    op.add_column('guardians', sa.Column('child_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('guardians_child_id_fkey', 'guardians', 'students', ['child_id'], ['id'], ondelete='CASCADE')
    op.add_column('administrators', sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('administrators_student_id_fkey', 'administrators', 'students', ['student_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
