"""revision

Revision ID: 0aef2e6ae23f
Revises: 9019c2b5812d
Create Date: 2023-03-16 13:22:41.929960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0aef2e6ae23f'
down_revision = '9019c2b5812d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
