"""admin/news relationship

Revision ID: 110068cdf845
Revises: 7d3925be566e
Create Date: 2023-03-07 10:52:18.826798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '110068cdf845'
down_revision = '7d3925be566e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
