"""fix error

Revision ID: 1be86fb46240
Revises: b46bd0b4fe7e
Create Date: 2023-03-16 13:41:13.908762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1be86fb46240'
down_revision = 'b46bd0b4fe7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
