"""updated student_subject table

Revision ID: 2a948d5764cc
Revises: 5dab0e84f3ca
Create Date: 2023-03-20 08:26:09.148823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a948d5764cc'
down_revision = '5dab0e84f3ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('student_subjects_student_id_fkey', 'student_subjects', type_='foreignkey')
    op.create_foreign_key(None, 'student_subjects', 'students', ['student_id'], ['student_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'student_subjects', type_='foreignkey')
    op.create_foreign_key('student_subjects_student_id_fkey', 'student_subjects', 'students', ['student_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
