"""create students table

Revision ID: 2c42294a1c61
Revises: 3a1158160383
Create Date: 2023-03-07 06:54:51.847048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c42294a1c61'
down_revision = '3a1158160383'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('teacher_id', sa.Integer(), nullable=False))
    op.add_column('students', sa.Column('parent_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'students', 'administrators', ['teacher_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'students', 'guardians', ['parent_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.drop_column('students', 'parent_id')
    op.drop_column('students', 'teacher_id')
    # ### end Alembic commands ###
