"""create news table

Revision ID: 3a1158160383
Revises: ed32b4b6ef64
Create Date: 2023-03-06 07:27:01.354430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a1158160383'
down_revision = 'ed32b4b6ef64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('author_id', sa.Integer(), nullable=False))
    op.drop_constraint('news_author_fkey', 'news', type_='foreignkey')
    op.create_foreign_key(None, 'news', 'administrators', ['author_id'], ['id'], ondelete='CASCADE')
    op.drop_column('news', 'author')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('author', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'news', type_='foreignkey')
    op.create_foreign_key('news_author_fkey', 'news', 'administrators', ['author'], ['id'], ondelete='CASCADE')
    op.drop_column('news', 'author_id')
    # ### end Alembic commands ###
