"""students table

Revision ID: 425f7b5067b8
Revises: 9e18eb5ac3ac
Create Date: 2023-03-12 05:37:31.532292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '425f7b5067b8'
down_revision = '9e18eb5ac3ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
