"""new revisions

Revision ID: 57e9cc1c17f2
Revises: 018ed12412fe
Create Date: 2023-03-16 13:26:29.992493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57e9cc1c17f2'
down_revision = '018ed12412fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
