"""fix relationship between subject and results error

Revision ID: 596d48d792b1
Revises: 01b0be59fced
Create Date: 2023-03-16 14:10:10.296407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '596d48d792b1'
down_revision = '01b0be59fced'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('results', sa.Column('teacher_subject_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'results', 'subjects', ['teacher_subject_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'results', type_='foreignkey')
    op.drop_column('results', 'teacher_subject_id')
    # ### end Alembic commands ###
