"""fix relationship between subject and results error

Revision ID: 6dc90200de7e
Revises: 596d48d792b1
Create Date: 2023-03-16 14:12:59.391574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6dc90200de7e'
down_revision = '596d48d792b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('results_student_subject_id_fkey', 'results', type_='foreignkey')
    op.drop_constraint('results_teacher_subject_id_fkey', 'results', type_='foreignkey')
    op.create_foreign_key(None, 'results', 'student_subjects', ['student_subject_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'results', 'teacher_subjects', ['teacher_subject_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'results', type_='foreignkey')
    op.drop_constraint(None, 'results', type_='foreignkey')
    op.create_foreign_key('results_teacher_subject_id_fkey', 'results', 'subjects', ['teacher_subject_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('results_student_subject_id_fkey', 'results', 'subjects', ['student_subject_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
