"""fix relationship between subject and results error

Revision ID: 700c37862d89
Revises: dda097178602
Create Date: 2023-03-19 16:28:23.960722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '700c37862d89'
down_revision = 'dda097178602'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
