"""revision

Revision ID: 9019c2b5812d
Revises: 2e2b7bd4332e
Create Date: 2023-03-16 13:12:18.177488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9019c2b5812d'
down_revision = '2e2b7bd4332e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
