"""updated the students

Revision ID: 96dc39f527d7
Revises: b1c367ffd6e4
Create Date: 2023-03-15 13:18:36.503682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96dc39f527d7'
down_revision = 'b1c367ffd6e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('department', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'department')
    # ### end Alembic commands ###
