"""generate all tables

Revision ID: 971ec511780f
Revises: d16f598a168c
Create Date: 2023-03-15 15:13:19.690028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '971ec511780f'
down_revision = 'd16f598a168c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('student_id', sa.String(), nullable=False))
    op.drop_constraint('students_studentID_key', 'students', type_='unique')
    op.create_unique_constraint(None, 'students', ['student_id'])
    op.drop_column('students', 'studentID')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('studentID', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'students', type_='unique')
    op.create_unique_constraint('students_studentID_key', 'students', ['studentID'])
    op.drop_column('students', 'student_id')
    # ### end Alembic commands ###
