"""create students table

Revision ID: 9b4b035419b4
Revises: 2c42294a1c61
Create Date: 2023-03-07 08:00:23.550591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b4b035419b4'
down_revision = '2c42294a1c61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('administrators', sa.Column('student_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'administrators', 'students', ['student_id'], ['id'], ondelete='CASCADE')
    op.add_column('guardians', sa.Column('child_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'guardians', 'students', ['child_id'], ['id'], ondelete='CASCADE')
    op.add_column('news', sa.Column('image', sa.String(), nullable=True))
    op.drop_constraint('students_parent_id_fkey', 'students', type_='foreignkey')
    op.drop_constraint('students_teacher_id_fkey', 'students', type_='foreignkey')
    op.drop_column('students', 'parent_id')
    op.drop_column('students', 'teacher_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('teacher_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('students', sa.Column('parent_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('students_teacher_id_fkey', 'students', 'administrators', ['teacher_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('students_parent_id_fkey', 'students', 'guardians', ['parent_id'], ['id'], ondelete='CASCADE')
    op.drop_column('news', 'image')
    op.drop_constraint(None, 'guardians', type_='foreignkey')
    op.drop_column('guardians', 'child_id')
    op.drop_constraint(None, 'administrators', type_='foreignkey')
    op.drop_column('administrators', 'student_id')
    # ### end Alembic commands ###
