"""project attribute

Revision ID: 9e18eb5ac3ac
Revises: f6851a13e210
Create Date: 2023-03-12 05:17:27.379770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e18eb5ac3ac'
down_revision = 'f6851a13e210'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teachers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('mobile_no', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('class_taught', sa.String(), nullable=True),
    sa.Column('subject_taught', sa.String(), nullable=True),
    sa.Column('reg_date', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.alter_column('students', 'teacher_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'students', 'teachers', ['teacher_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.alter_column('students', 'teacher_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_table('teachers')
    # ### end Alembic commands ###
