"""Updated teacher/students and parent/child relationship

Revision ID: a7827d2b631d
Revises: d851997780eb
Create Date: 2023-03-07 10:10:38.906585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7827d2b631d'
down_revision = 'd851997780eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
