"""admin/news relationship

Revision ID: ac8b8c8a9d54
Revises: b5761d02c3ed
Create Date: 2023-03-07 10:45:32.175516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac8b8c8a9d54'
down_revision = 'b5761d02c3ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('class_taught', sa.String(), nullable=False),
    sa.Column('reg_date', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('last_login', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('news', sa.Column('updated', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False))
    op.create_foreign_key(None, 'news', 'admins', ['author_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'students', 'admins', ['teacher_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.drop_constraint(None, 'news', type_='foreignkey')
    op.drop_column('news', 'updated')
    op.drop_table('admins')
    # ### end Alembic commands ###
