"""fix error

Revision ID: b46bd0b4fe7e
Revises: 57e9cc1c17f2
Create Date: 2023-03-16 13:34:28.895269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b46bd0b4fe7e'
down_revision = '57e9cc1c17f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
