"""admin/news relationship

Revision ID: b5761d02c3ed
Revises: a7827d2b631d
Create Date: 2023-03-07 10:32:35.063259

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b5761d02c3ed'
down_revision = 'a7827d2b631d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('class_taught', sa.String(), nullable=False),
    sa.Column('reg_date', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('last_login', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('administrators')
    op.drop_constraint('news_author_id_fkey', 'news', type_='foreignkey')
    op.create_foreign_key(None, 'news', 'admins', ['author_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('students_teacher_id_fkey', 'students', type_='foreignkey')
    op.create_foreign_key(None, 'students', 'admins', ['teacher_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.create_foreign_key('students_teacher_id_fkey', 'students', 'administrators', ['teacher_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'news', type_='foreignkey')
    op.create_foreign_key('news_author_id_fkey', 'news', 'administrators', ['author_id'], ['id'], ondelete='CASCADE')
    op.create_table('administrators',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('class_taught', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('reg_date', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('last_login', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='administrators_pkey')
    )
    op.drop_table('admins')
    # ### end Alembic commands ###
