"""unique attribute

Revision ID: bd606fb354d2
Revises: 121303952fbd
Create Date: 2023-03-07 12:23:55.440838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd606fb354d2'
down_revision = '121303952fbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
