"""Teacher and Guarrdian table

Revision ID: d5a5b22956c1
Revises: 425f7b5067b8
Create Date: 2023-03-12 06:05:45.695510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5a5b22956c1'
down_revision = '425f7b5067b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guardians', sa.Column('title', sa.String(), nullable=False))
    op.add_column('teachers', sa.Column('title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teachers', 'title')
    op.drop_column('guardians', 'title')
    # ### end Alembic commands ###
