"""Updated teacher/students and parent/child relationship

Revision ID: d851997780eb
Revises: 08af7e40b2a1
Create Date: 2023-03-07 10:03:39.303857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd851997780eb'
down_revision = '08af7e40b2a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
