"""fix relationship between subject and results error

Revision ID: dda097178602
Revises: 6dc90200de7e
Create Date: 2023-03-16 14:20:27.270324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dda097178602'
down_revision = '6dc90200de7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
