"""unique attribute

Revision ID: de86b58f1054
Revises: 9756965606ec
Create Date: 2023-03-07 12:36:35.701574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de86b58f1054'
down_revision = '9756965606ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
