"""create news table

Revision ID: ed32b4b6ef64
Revises: 93c44ee8bdcb
Create Date: 2023-03-06 07:21:35.348210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed32b4b6ef64'
down_revision = '93c44ee8bdcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('author', sa.Integer(), nullable=False),
    sa.Column('date', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['author'], ['administrators.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('administrators', sa.Column('name', sa.String(), nullable=False))
    op.add_column('administrators', sa.Column('email', sa.String(), nullable=False))
    op.add_column('administrators', sa.Column('password', sa.String(), nullable=False))
    op.add_column('administrators', sa.Column('class_taught', sa.String(), nullable=False))
    op.add_column('administrators', sa.Column('reg_date', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False))
    op.add_column('administrators', sa.Column('last_login', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False))
    op.add_column('guardians', sa.Column('name', sa.String(), nullable=False))
    op.add_column('guardians', sa.Column('email', sa.String(), nullable=False))
    op.add_column('guardians', sa.Column('password', sa.String(), nullable=False))
    op.add_column('guardians', sa.Column('reg_date', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False))
    op.add_column('guardians', sa.Column('last_login', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guardians', 'last_login')
    op.drop_column('guardians', 'reg_date')
    op.drop_column('guardians', 'password')
    op.drop_column('guardians', 'email')
    op.drop_column('guardians', 'name')
    op.drop_column('administrators', 'last_login')
    op.drop_column('administrators', 'reg_date')
    op.drop_column('administrators', 'class_taught')
    op.drop_column('administrators', 'password')
    op.drop_column('administrators', 'email')
    op.drop_column('administrators', 'name')
    op.drop_table('news')
    # ### end Alembic commands ###
