"""fix relationship between subject and results error

Revision ID: ee25f27a6c93
Revises: 700c37862d89
Create Date: 2023-03-19 17:13:09.089989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee25f27a6c93'
down_revision = '700c37862d89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
